#!/bin/sh
set -eu
test -n "${FACILITATOR_DB_PASSWORD:-}" && test -n "${YACI_DB_PASSWORD:-}"
test "${FACILITATOR_DB_PASSWORD}" != "${YACI_DB_PASSWORD}"
test "${FACILITATOR_DB_PASSWORD}" != "${POSTGRES_PASSWORD}"
test "${YACI_DB_PASSWORD}" != "${POSTGRES_PASSWORD}"
psql -X -q -v ON_ERROR_STOP=1 -U postgres -d postgres <<'SQL'
\getenv fpass FACILITATOR_DB_PASSWORD
\getenv ypass YACI_DB_PASSWORD
SET password_encryption = 'scram-sha-256';
SELECT 'CREATE ROLE facilitator LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS'
 WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'facilitator') \gexec
SELECT 'CREATE ROLE yaci_store LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS'
 WHERE NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'yaci_store') \gexec
ALTER ROLE facilitator WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS PASSWORD :'fpass';
ALTER ROLE yaci_store WITH LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT NOREPLICATION NOBYPASSRLS PASSWORD :'ypass';
CREATE SCHEMA IF NOT EXISTS facilitator AUTHORIZATION facilitator;
CREATE SCHEMA IF NOT EXISTS yaci_store AUTHORIZATION yaci_store;
ALTER SCHEMA facilitator OWNER TO facilitator;
ALTER SCHEMA yaci_store OWNER TO yaci_store;
REVOKE ALL ON SCHEMA facilitator, yaci_store FROM PUBLIC;
REVOKE ALL ON SCHEMA facilitator FROM yaci_store;
REVOKE ALL ON SCHEMA yaci_store FROM facilitator;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT CONNECT, CREATE ON DATABASE postgres TO facilitator, yaci_store;
SQL
